#!/bin/bash
ABS_PATH="$(readlink -f "$0")"
CONTAINER_NAME="$(basename "$(dirname "$ABS_PATH")")"

# Build Docker Image
docker build \
    --tag ${CONTAINER_NAME}:latest \
    .
# Run Container
docker run -p 8000:8000 \
	--detach \
	--interactive \
	--tty \
	--rm \
	--volume $(pwd):/app \
	--name $CONTAINER_NAME \
	$CONTAINER_NAME
